spring:
  application:
    name: map-service

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/bowchat?currentSchema=map_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

map:
  client:
    base-url: ${MAP_CLIENT_BASE_URL:https://dapi.kakao.com}
    api-key: ${MAP_CLIENT_API_KEY:}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8084
