spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:application-prod.yml

---
spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: com.example.bowchat.kafka,com.example.bowchat.kafka.*,java.util,java.lang
    admin:
      auto-create: false
  web:
    resources:
      add-mappings: false

logging:
  level:
    net.javacrumbs.shedlock: DEBUG