spring:
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.bowchat.kafka, com.example.bowchat.chatmessage.dto
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.bowchat.kafka.ChatEvent

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://13.54.183.123:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600000
    refresh-token-expiration: 1209600000

  datasource:
    url: jdbc:postgresql://postgres:5432/bowchat
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate.default_batch_fetch_size: 50

  data:
    mongodb.uri: ${MONGODB_URI}
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0

decorator:
  datasource:
    p6spy.enable-logging: true

file:
  upload-dir: /app/uploads

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: bowchat-image-bucket
    stack:
      auto: false
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: "never"
  metrics:
    tags:
      application: "bowchat"
server:
  tomcat:
    threads:
      max: 400