name: Deploy BowChat to EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  APP_NAME: bowchat
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ubuntu
  EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
  PROJECT_DIR: /home/ubuntu/bowchat
  JAR_NAME: bowchat-0.0.1-SNAPSHOT.jar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'



      - name: Debug — show file list
        run: | 
          pwd
          ls -R src/main/resources

      - name: Set Env variables
        uses: microsoft/variable-substitution@v1
        with:
          files: src/main/resources/application-prod.yml
        env:
          DB_USERNAME: ${{ secrets.POSTGRES_USER }}
          DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}

      - name: Build Spring Boot JAR (skip tests)
        run: ./gradlew bootJar -x test

      - name: Transfer project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          source: "./build/libs/${{ env.JAR_NAME }}, ./docker-compose.yml, ./Dockerfile, ./src/main/resources/application-prod.yml"
          target: "${{ env.PROJECT_DIR }}"

      - name: Connect to EC2 and Deploy via Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            set -e
            cd ${{ env.PROJECT_DIR }}

            echo "EC2 연결 완료"
            docker compose down || true
            docker compose up -d --build
            echo " 배포 완료"